# Generated by Django 5.0.2 on 2024-04-25 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0017_semester_alter_user_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='sem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.semester'),
        ),
    ]
