# Generated by Django 5.0.2 on 2024-04-25 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0018_alter_class_sem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='sem',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Semester',
        ),
    ]
